### PR TITLE
#78: Moves confluence documentation to GitHub.

### PR DESCRIPTION
**Pull request by hemanik**
#### Short description of what this resolves:
Consolidates Drone Documentation from Confluence to GitHub Project Repo.

#### Changes proposed in this pull request:

- Added Documentation to the Docs section of the Project Repo

**Fixes**: #78

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
It's quite a long readme. Wouldn't it make sense to slice it to subsection files like in Cube?

**Comment by MatousJobanek** [comment]
I don't have problem with the length, but I would welcome at least a table of content at the very beginning

**Comment by bartoszmajsak** [comment]
> I don't have problem with the length, but I would welcome at least a table of content at the very beginning

ToC is augenerated, see http://arquillian.org/arquillian-cube

**Comment by MatousJobanek** [comment]
I meant inside of the file so the content is visible also in the github repo... 
But yeah, this is fine...

**Comment by bartoszmajsak** [comment]
We can try that, not sure if works out of the box on GH. Ideally we should have slim readme with the link to the documentation.

**Comment by hemanik** [comment]
Fixing it. 
@MatousJobanek  @bartoszmajsak  , please have a look at this, https://github.com/arquillian/arquillian-extension-persistence/pull/58.
If this looks fine, I'll do it the same way for the all other extensions.

**Comment by MatousJobanek** [comment]
LGTM, when you have divided into several pages no table of contents is necessary. 
Thanks a lot

**Comment by bartoszmajsak** [comment]
Thank you @hemanik. Pushed upstream @2461c08bf. Life at http://arquillian.org/arquillian-extension-drone/

**Pull request closed without merging**
