### PR TITLE
feat: compatibility with Selenium 4.3.0

### LINKED ISSUE #347: Compatibility with Selenium 4.3.0
It'd be great to have the possibility smoothly interact with Selenium 4.3.0. 

I'll also send PR for the Graphene, but the Drone needs to be done sooner.

### PR DESCRIPTION
**Pull request by mabartos**
Closes #347

It'd be great to have the possibility smoothly interact with Selenium 4.3.0.

I'll also send PR for the Graphene, but the Drone needs to be done sooner.

@bartoszmajsak Hello! Could you please take a look at it? Moreover, would it be possible to release a new version of the Drone with these changes?

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Thanks a lot @mabartos. I'll take care of it this afternoon!

**Comment by mabartos** [comment]
@bartoszmajsak Thanks! I've just noticed, that it requires some additional changes regarding the Capabilities and WebDriver factories. I'll take a look at it.

**Review by bartoszmajsak — APPROVED** [review]
Thank you!

**Comment by mabartos** [comment]
@bartoszmajsak Thanks for the merge! Is it possible to release a new alpha version with these changes?

**Comment by bartoszmajsak** [comment]
It's out.

**Pull request merged**
