### PR TITLE
Fix for defect in username and accessKey extraction from Url.

### PR DESCRIPTION
**Pull request by singhravik**
Without this fix an error of 'java.lang.StringIndexOutOfBoundsException: String index out of range: -3' is seen.

##### Issue Overview
Defect in SauceLab extension. The logic for extracting username and accessKey extraction from Url seems to be defective. It throws error of 'java.lang.StringIndexOutOfBoundsException: String index out of range: -3'

##### Expected Behaviour
username and accessKey should get parsed out.

##### Current Behaviour
It throws error of 'java.lang.StringIndexOutOfBoundsException: String index out of range: -3'

##### Steps To Reproduce
1. Use the below section of configuration in arquillian.xml and use the latest artifact 2.5.1 of extension.
2. Start the test and the extension fails at Line # 104 of extension/arquillian-drone-saucelabs-extension/src/main/java/org/arquillian/drone/saucelabs/extension/webdriver/SauceLabsDriverFactory.java
   username = url.substring(url.lastIndexOf("://") + 3, url.indexOf(":"));

##### Additional Information
Use this configuration :

saucelabs
rsingh_001
/Users/rsing34/Develop/sc
https://rsingh_001:[123456-123456-123456-123456e@ondemand.saucelabs.com](mailto:123456-123456-123456-123456e@ondemand.saucelabs.com):443/wd/hub
123456-123456-123456-123456
true
true
chrome
macOS 10.13
69.0
2.53.0

### CODE REVIEW

**Comment by singhravik** [comment]
Refer to Issue: https://github.com/arquillian/arquillian-extension-drone/issues/147

**Comment by bartoszmajsak** [comment]
Many thanks for your contribution @singhravik.

I'm wondering if that piece of functionality (parsing URL) could be extracted to separated unit and test in isolation? Could you provide some tests for it?

**Comment by singhravik** [comment]
Added the test configuration that fails on master branch.

**Comment by Mickeyrourkeske** [comment]
Anything happening here?
It's a real bummer.

**Comment by bartoszmajsak** [comment]
Thanks for your contribution. I took the liberty to rework it in 34a956 by using `UserInfo` already parsed in `URL` object created in that method. I left the attribution on the commit though.

**Pull request closed without merging**
