### PR TITLE
Fixing wrong profiles from pom.xml

### PR DESCRIPTION
**Pull request by dipak-pawar**
#### Short description of what this resolves:
Fixing pom profiles for htmlUnit

#### Changes proposed in this pull request:
- We have used htmlUnit as a browser in implementation, where at the same time we are using `htmlunit` in profiles

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
I'm not sure what it fixes. We cannot specify `htmlunit` as a browser name for drone?

**Comment by dipak-pawar** [comment]
@bartoszmajsak we have to use htmlUnit not `htmlunit` in drone. Or we have to check for both & make it downcase in implementation

**Comment by bartoszmajsak** [comment]
I think we should support both then and leave profile as it was before

**Comment by dipak-pawar** [comment]
:+1:

**Comment by bartoszmajsak** [comment]
Thanks for spotting it!

**Comment by bartoszmajsak** [comment]
If you are willing to fix it we can use this PR to implement this feature.

**Comment by dipak-pawar** [comment]
cc @MatousJobanek

**Comment by MatousJobanek** [comment]
Thx for the fix - yeah, this is a better solution than just fixing the wrong profile configuration (give us more possibilities). 
However, we will need additional changes in the test suite and in the implementation. 

I would start with the pom with the profiles - you need to cover also the second option: `htmlUnit `

Then, if I run the test suite with `htmlUnit` property, I get several times an Exception:
~~~
java.lang.IllegalStateException: Unable to initialize WebDriver instance. Please specify a valid browser instead of htmlUnit. Available options are: internetExplorer, edge, opera, chrome, safari, phantomjs, firefox, htmlUnit
~~~
This is probably because you didn't change the values in `BrowserCapabilitiesList` and the `WebDriverConfiguration` still returns original string when `getBrowser()` method is called.

If I run with `htmlunit` I get an error for `TestRemoteWebDriverFactorySessionStoring` so you need to modify it accordingly. 

You also get an error for the test case: `TestReusableRemoteWebDriver` - this one seems to be caused by a bug in HtmlUnit so we cannot anyhow influence it. A possible workaround is seting `setThrowExceptionOnScriptError` option of the WebClient to `false` but we need to have the functionality first. For now you can skip the test.

**Comment by dipak-pawar** [comment]
@MatousJobanek Please have a look into this.

**Comment by MatousJobanek** [comment]
Looks good now, thank you @dipak-pawar 👍

**Pull request merged**
